### ISSUE TITLE
Authorization for privileged tasks 

### ISSUE THREAD

**Issue by gothub** [DataONEorg/bookkeeper#9]
Several REST calls require the role
```
    @RolesAllowed("CN=urn:node:CN,DC=dataone,DC=org")
```
for example [here](https://github.com/DataONEorg/bookkeeper/blob/master/src/main/java/org/dataone/bookkeeper/resources/QuotasResource.java#L171) 

Is this still the desired way to authorize privileged operations such as create quotas? As an alternative, could a list of 'super-admin' users be defined?

**Comment by csjx** [comment]
Yes, I had added `RolesAllowed` annotations at first because it was the declared way in Dropwizard to restrict access.  But it really works best when there is an authorization layer that defines roles (really groups), and then authorizes members of the role.  We could add that layer into `DataONEAuthHelper`, or we could just use `PermitAll` annotations and delegate the authorization to calls to `isAdmin()` which we are already doing in other places.  That said, for certain calls (like `QuotasResource.create()`), they should be limited to a different list of admin subjects, and wouldn't include the MN subjects.  I think we could create `dataone.bookkeeperAdminSubjects` initially with the ORCIDs for Matt, Dave, Lauren, Peter, Jing, and Chris.  The `dataone.adminSubjects` would include the MN subjects running Metacat that need most but not all access.

**Comment by csjx** [comment]
In the second secenario where we use `PermitAll`, we'd need an `isBookkeeperAdmin()` method as well.
